#### 넘파이(numpy)
- pandas, 머신러닝 라이브러리에서 기본적으로 필요한 라이브러리
- 파이썬 list 보다 빠름 / 메모리는 적게 사용
- 빌트인 함수 : 선형대수, 통계 관련 여러 함수 내장

In [1]:
import numpy as np


In [33]:
# 1차원 벡터 생성
array1 = np.array([1, 2, 3])
array1

array([1, 2, 3])

In [ ]:
print(type(array1))
print(array1.shape) 

<class 'numpy.ndarray'>
(3,)


In [4]:
# 2차원
array2 = np.array([[1, 2, 3], [4, 5, 6]])
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(type(array2))
print(array2.shape) # 2행 3열

<class 'numpy.ndarray'>
(2, 3)


In [6]:
# 파이썬 리스트
list1 = [1, 2, 'a', 'b', True]
list1

[1, 2, 'a', 'b', True]

In [8]:
array3 = np.array([1, 2, 3.1])
print(array3.dtype)
print(type(array3))

float64
<class 'numpy.ndarray'>


In [9]:
array4 = np.array(list1)
print(array4.dtype)

<U21


- ndarray 다양한 방법으로 생성하기

In [12]:
np.arange(5, 10, 2)

array([5, 7, 9])

In [13]:
# dtype 지정 안하는 경우 float
np.zeros(5, dtype="int32")

array([0, 0, 0, 0, 0], dtype=int32)

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.ones((3, 2, 1))

array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]])

In [ ]:
# n행 m렬 x로 가득 채우기
np.full((3, 4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
# 단위 행렬
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [40]:
array1 = np.arange(1, 10)

In [46]:
# 알아서 지정 : -1 
array2.reshape(-1, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [49]:
array2.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6]])

In [28]:
# 임의의 수 ndarray 생성
np.random.rand(2, 3)

array([[0.25541645, 0.1703307 , 0.29243758],
       [0.475994  , 0.80466647, 0.82132366]])

In [58]:
# 행렬 사칙연산
x = np.array([[4, 4, 4], [8, 8, 8]])
y = np.array([[1, 1, 1], [2, 2, 2]])

In [60]:
x + y

array([[ 5,  5,  5],
       [10, 10, 10]])

In [59]:
x // y

array([[4, 4, 4],
       [4, 4, 4]])

In [61]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8], [9, 10], [11, 12]])
print(x)
print(y)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [62]:
np.dot(x, y)

array([[ 58,  64],
       [139, 154]])

In [63]:
# 전치 행렬
np.transpose(x)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
v = np.array([3, 4])

# nprm(ord)
np.linalg.norm(v)

np.float64(5.0)